### ISSUE TITLE
InvalidInjectionException on onBreak

### ISSUE THREAD

**Issue by Crec0** [Super-Santa/EssentialAddons#1]
Seems like there's an invalid target for onBreak injection
[Crash Log](https://github.com/Super-Santa/EssentialAddons/files/6912224/latest.log)

**Comment by senseiwells** [comment]
I can't reproduce in my 1.17.1 client, but I changed the method qualifier so see [if this fixes it](https://cdn.discordapp.com/attachments/559400132710236160/871327035820240906/essentialaddons-1.17.1-1.0.1.jar)

**Comment by Crec0** [comment]
Yep, that seems to have fixed the issues. I can launch and and all features work perfectly fine :)
Thanks

**Comment by senseiwells** [comment]
The only thing I changed was the method qualifier so I guess that fixed it, although the mod was working fine on my client, I just got that from the the crash report.
