### ISSUE TITLE
Players can get out of Drowning with Camera Mode.

### ISSUE THREAD

**Issue by LunchBox951** [Super-Santa/EssentialAddons#15]
**Describe the bug**
If a player is drowning in water, by using the /cs command and putting their character over the water they can refill their air bar.

**General Info**
Mod Version: 1.0.7
Minecraft Version: 1.18.1

**To Reproduce**
1. Start drowning in survival mode
2. Use /cs to switch to spectator
3. Fly above the water into air
4. Use /cs to be taken back to your original location with full air

**Expected behavior**
You shouldn't be able to /cs if drowning, or it should retain your air bar when taken back.

**Comment by Super-Santa** [comment]
@LunchBox951 I've added a condition to the rule `cameraModeSurvivalRestrictions` which doesn't allow players to enter spectator mode if they are submerged in water. This should stop people from being able to get out of drowning. You can download the new jar here: https://github.com/Super-Santa/EssentialAddons/releases/tag/1.0.7
