### ISSUE TITLE
ReloadFakePlayerActions don't work

### ISSUE THREAD

**Issue by byelzovski** [Super-Santa/EssentialAddons#16]
**Describe the bug**
when i restart the world, the fake player is just stopped

**General Info**
Mod Version: 1.0.7
Minecraft Version: 1.17.1 and 1.18.1(tested on both versions)
List of other mods: only gnembon's carpet and essentialaddons

**To Reproduce**
1-I checked if the ReloadFakePlayer and ReloadFakePlayerActions rules were enabled.
2-Summoned a player
3-restarted the world
4-I ran the command "/player steve move forward", and disconnected while he was walking (I also tested it with the player attacking)
5-Rejoined de world, and the player was stopped.

**Expected behavior**
I expected that when restarting the world, the bot was performing the same action as before disconnecting

**Screenshots / Videos**
1.17.1:   https://youtu.be/j0D97cPI5zo
1.18.1:   https://youtu.be/-2Ntq_gL31I

**Additional info**
I just wanna use gnembon's carpet mod instead skyrising's quick carpet(because i can create scarpet scripts and use anothers extensions, like yours), but for this i need persistent players.

**Comment by senseiwells** [comment]
This will be fixed in next release

**Comment by senseiwells** [comment]
https://github.com/Super-Santa/EssentialAddons/releases/tag/1.1.0
