### ISSUE TITLE
CameraModeTeleportBlacklist does'n seem to work

### ISSUE THREAD

**Issue by GaviMC** [Super-Santa/EssentialAddons#18]
**Describe the bug**
I don't know if i've just misunderstood the description, but from what I think it should do, I can't get the "CameraModeTeleportBlacklist" to work.

**General Info**
Mod Version: 1.0.7
Minecraft Version: I've only tested it in 1.17.1 
List of other mods: Carpet mod + EssentialAddons

**To Reproduce**
1. I've enabled both "/carpet commandCameraMode" and "/carpet cameraModeTeleportBlacklist" carpet rules.
2. When I type /cs and try to teleport to a player, it still let's me teleport.

**Expected behavior**
I expected that it would prevent me from teleport to other survival players.

**Comment by senseiwells** [comment]
The way this feature works is that once it is enabled a player can type `/subscribe teleportBlacklist` and this toggles whether players can teleport to them, so each player decides whether they can be teleported to
