### ISSUE TITLE
essential addons with essential client crash the game

### ISSUE THREAD

**Issue by Pi3tro88** [Super-Santa/EssentialAddons#19]
if i try to launch the game with only carpet mod, fabric api, senseiwell's essential client and essential addons, the game crashes

Mod Version: 1.0.7
Minecraft Version: 1.17.1
List of other mods: carpet mod 1.4.56, fabric api 0.54.2, essential client 1.1.2

**To Reproduce**
Steps to reproduce the behavior: try  to start minecraft

**Expected behavior**
A clear and concise description of what you expected to happen: minecraft should start without problems

**Crash Report / Lastest Log**
Upload your crash report or latest log to help us figure out what's going on: 
[latest.log](https://github.com/Super-Santa/EssentialAddons/files/7877565/latest.log)

**Screenshots / Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional info**
Add any other info about the problem here.

**Comment by Crec0** [comment]
Already patched. Will be fixed in next release.

**Comment by Pi3tro88** [comment]
Top
