### ISSUE TITLE
JsonSyntaxException while reading camera data

### ISSUE THREAD

**Issue by Crec0** [Super-Santa/EssentialAddons#2]
i was doing nothing but restarting my minecraft instance and this happened. Guess the camera data saving is not saving in proper syntax and when reading it crashes.
[Crash log](https://github.com/Super-Santa/EssentialAddons/files/6913818/latest.log)
*subscribedata.json* contains this data 
```json
{
  "215133b1-00b9-481c-8fd9-875d0eab40c7": {
    "isSubscribedCarefulBreak": true,
    "isSubscribedTeleportBlacklist": false
  }
}
```

**Comment by Crec0** [comment]
Looks correct to me idk why the code didn't like it. weird.

**Comment by senseiwells** [comment]
Camera data is stored seperately from subscribe data, the camera data file will be deleted if there is no data to be stored, so if you stop the server with no players in cs there is no data to store so it just deletes it, I will remove the log.
[this should fix it](https://cdn.discordapp.com/attachments/559400132710236160/871686348099190804/essentialaddons-1.17.1-1.0.3.jar)
