### ISSUE TITLE
You Got a Maven you Have this Hosted on?

### ISSUE THREAD

**Issue by JacktheDevel0per** [Super-Santa/EssentialAddons#20]
I am Trying to Inject into Your Mod For Compat if its Present to Edit Some Stuff so My Commands / My Stuff Works while your mod is loaded and was wondering if I had to Download it or if you have a maven so its easy to update and stuff.

**Comment by senseiwells** [comment]
No there's no maven, I would just clone it and make a pr for compat

**Comment by JacktheDevel0per** [comment]
It's not that kind of compat it's a command that you register that I disable, it's all good I just did it thru mixins.

**Comment by senseiwells** [comment]
cool
