### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by itsdinkd** [Super-Santa/EssentialAddons#21]
Would there be a way to be able to give permissions to use certain commands using something like LuckyPerms? 
like essentialaddons.command.gm

**Comment by senseiwells** [comment]
Probably not

**Comment by jiriks74** [comment]
AFAIK, it isn't in this plugin. But would be a really nice feature as some commands, like `/heal` are only here. (`Bssentials` isn't for `1.19.2`)

**Comment by senseiwells** [comment]
Information on permissions on the README.
The latest version of the mod can be downloaded [here](https://github.com/Super-Santa/EssentialAddons/actions/runs/4369152189).
