### ISSUE TITLE
Requested enhancement to "essentialCarefulBreak" --> "essentialDropToInventory"

### ISSUE THREAD

**Issue by SleepyCatten** [Super-Santa/EssentialAddons#22]
**Describe the feature**
Rule Name: essentialDropToInventory
Description: Mining blocks or loot dropped from mobs/entities will be put straight into your inventory.
Options:
- activated: false, true
- requires crouch/sneak: false, true
Categories: ESSENTIAL, COMMAND, SURVIVAL, FEATURE

**Expected behavior**
This will mirror the functionality of "CarefulBreak" and expand it to include loot drops from mobs/entities. It will be off by default. Players should have the option to toggle each option for themselves.

**Additional info**
There is a Spigot plugin which does this called "Drop2Inventory Plus" (https://www.spigotmc.org/resources/%E2%AD%90-drop2inventory-plus-%E2%AD%90.87784/), along with some other features. I have listed the core functionality only for this request. Another developer has implemented this partly as "carefulBreakNoSneak", but without the mob loot drops included. (https://github.com/enjarai/carpet-addons)

**Comment by senseiwells** [comment]
This will be included in the next release

**Comment by senseiwells** [comment]
https://github.com/Super-Santa/EssentialAddons/releases/tag/1.1.0
