### ISSUE TITLE
Updated to 1.1.0 and getting this error now

### ISSUE THREAD

**Issue by mrniddala** [Super-Santa/EssentialAddons#26]
Hello, I hope it helps.
Thanks you.

[crash-2022-02-27_16.29.16-server.txt](https://github.com/Super-Santa/EssentialAddons/files/8149018/crash-2022-02-27_16.29.16-server.txt)

**Comment by senseiwells** [comment]
Use https://github.com/gnembon/fabric-carpet/releases/tag/1.4.56

**Comment by senseiwells** [comment]
Redownload https://github.com/Super-Santa/EssentialAddons/releases/tag/1.1.0 and it should be fixed
