### ISSUE TITLE
Error loading class: carpet/patches/NetworkManagerFake - "Invalid player data" - "Couldn't place player in world"

### ISSUE THREAD

**Issue by SleepyCatten** [Super-Santa/EssentialAddons#29]
**Describe the bug**
Unable to connect to server with EssentialAddons installed

**General Info**
Mod Version: essentialaddons-1.18.1-1.1.0
Minecraft Version: 1.18.1
List of other mods: carpet-extra-1.18.1-1.4.57, fabric-api-0.46.6+1.18, fabric-carpet-1.18.1-1.4.57+v220119

**To Reproduce**
1. Set up a Fabric 1.18.1 server.
2. Install all mods listed above.
3. Connect to server.

**Expected behavior**
I would be able to log on without issue. (I can log in fine without essentials installed).

**Crash Report / Lastest Log**
Upload your crash report or latest log to help us figure out what's going on.
- log - https://gist.github.com/SleepyCatten/65d3a164505814de32b8efb7495147a9
- crash - https://gist.github.com/SleepyCatten/c9582a025de68b9a5891bf54428ab918

**Screenshots / Videos**
N/A

**Additional info**
N/A

**Comment by senseiwells** [comment]
Please use Fabric Carpet 1.4.56
