### ISSUE TITLE
Several features don't exist

### ISSUE THREAD

**Issue by muluffel** [Super-Santa/EssentialAddons#3]
stackableShulkerBoxesInPlayerInventories and stackableShulkersWithItems don't exist when trying to enable them using /carpet

**Comment by senseiwells** [comment]
Hi could you provide a list of your mods, what version you are using, and maybe a video of you showing the issue? 
Thanks

**Comment by muluffel** [comment]
Should I send it to you via mail?

senseiwells ***@***.***> schrieb am Di., 3. Aug. 2021, 00:35:

**Comment by senseiwells** [comment]
Just send a screenshot of your mods folder, attach the log file from when you were experiencing the issue, upload a video to youtube and link it and state the any remaining information.

**Comment by GeoffreyKarnbach** [comment]
Hello,
I can confirm that stacking shulkerboxes with items doesn't work for some reason.
