### ISSUE TITLE
Teleport bug in camera mode on multiplayer server

### ISSUE THREAD

**Issue by Crec0** [Super-Santa/EssentialAddons#4]
**Describe the bug**
If players travels in spectator mode (from /cs) anywhere, disconnect from the multiplayer server and  reconnect they get teleported to that new location in survival mode.

**General Info**
Mod Version: v1.0.3
Minecraft Version: 1.17.1
List of other mods: carpet, lithium, starlight, lazydfu, carpet extra, carpet tis, auto crafting table, hydrogen, textilebackup, servux, syncmatica, dynmap

**To Reproduce**
1. connect to multiplayer server with essential addons
2. go into spectator mode by doing /cs
3. travel somewhere or tp to some other player ( using spectator teleport feature )
4. disconnect from the server
5. reconnect
6. player will be at the new location they traveled at in survival mode

**Expected behavior**
Player shouldn't be put into survival mode on relog. ( That's how it works in single player if you try to recreate the bug. )

**Comment by senseiwells** [comment]
Can you send a copy of your server.properties file?

**Comment by Crec0** [comment]
[server.properties.txt](https://github.com/Super-Santa/EssentialAddons/files/7026605/server.properties.txt)
Here ya go. sorry for .txt extension. Had to bypass github file attachment thing

**Comment by senseiwells** [comment]
Yea it's because of a setting you have in your server.properties ``force-gamemode=true``, basically whenever you join it will force you into the set gamemode (which in your case is survival)

**Comment by Crec0** [comment]
Yep that seems to be the issue. Its fixed. Thank you
