### ISSUE TITLE
port light_queue logger from quickcarpet

### ISSUE THREAD

**Issue by Pi3tro88** [Super-Santa/EssentialAddons#44]
i suggest to port light_queue logger from quickcarpet, since to use quickcarpet u have to replace the "vanilla" carpet with it

**Comment by Super-Santa** [comment]
Carpet TIS Addition already has a light queue logger. 

https://github.com/TISUnion/Carpet-TIS-Addition/blob/master/docs/loggers.md#lightqueue

**Comment by Pi3tro88** [comment]
Oman Sorry I'm fukin stupid
