### ISSUE TITLE
Crash on server load

### ISSUE THREAD

**Issue by mrniddala** [Super-Santa/EssentialAddons#45]
Hello, I got this bug: https://pastebin.com/raw/5zCFVHbx

I was removing "memoryleakfix" and the server started normally.

But now when I try to join my world I get this error: https://pastebin.com/raw/7ijEvcmk
When I tried to use the command "save-all", I got this error: https://pastebin.com/raw/tRsu2EAD

I was disabling the mod for now and everything works as usual.
Greetings.

**Comment by senseiwells** [comment]
This should be fixed in https://github.com/Super-Santa/EssentialAddons/releases/tag/1.1.4
