### ISSUE TITLE
Editable Signs issues.

### ISSUE THREAD

**Issue by nogutsnoglory69** [Super-Santa/EssentialAddons#46]
I'm using 1.1.3 for 1.17.1 and the rule straight up just doesn't work. Are there any known incompatibilities? My server has the following mods: fabric carpet, carpet extra, carpet tis addition, chunk debug, dropfullcarts, essential addons, lithium, servux, and starlight. Right clicking on a sign, no matter if I'm sneaking or not, or if I'm in creative or survival does nothing. 

edit: ugh, forgot to turn off the disable sign gui feature in tweakeroo.. however it still doesn't work on my survival server. Both my creative and survival servers have the same mods. 

Also there are a bunch of typos in the description of it.

**Comment by senseiwells** [comment]
Thanks for the report, I have fixed the typos, I cannot seem to reproduce the inability to open the sign, I'm in 1.19 with the rule turned on while crouching in survival and it works perfectly fine, I have looked at other mods and nothing interferes with this, so I presume it's something on your end?

**Comment by nogutsnoglory69** [comment]
I have no idea what's causing it not to work on my survival server. I've tried copying over the carpet.conf file from my survival server onto my creative server and it still worked with it, so I don't think it's any rules that are interfering. Do you have any ideas on what else I could try? I'd love to be able to use this feature in survival.

**Comment by nogutsnoglory69** [comment]
I figured it out. The offhand needs to be empty too. Is this intentional? It's rather annoying since I have food in my offhand at all times.

**Comment by senseiwells** [comment]
Yup it's implemented like that so I assume it's intentional, this will be closed, if you want to make a feature request you are welcome to do so
