### ISSUE TITLE
crashes when Simple Voice Chat is installed

### ISSUE THREAD

**Issue by fibrowolf** [Super-Santa/EssentialAddons#49]
when essentials is installed on its own its fine and when Simple Voice Chat is installed on its own all is fine, as soon as you install both together it crashes the server , no i am using this on 1.19.1 so that could be the issue too

**Comment by senseiwells** [comment]
Could you please provide a crash report?

**Comment by SouthernPixel** [comment]
the same thing is happening to me as well

**Comment by senseiwells** [comment]
Thanks, for now if you disable reload fake players it should work. I'll add this to the todo list

**Comment by SouthernPixel** [comment]
Thanks. Will do, hopefully it'll get fixed soon because these mods are vital for me atm

**Comment by senseiwells** [comment]
I undid the patch in the latest commit as there were some issues in singleplayer, instead I will make a pull request to the Simple Voice Chat mod instead and this crash stems from their end.

**Comment by senseiwells** [comment]
Has been fixed in Simple Voice Chat \o/
https://github.com/henkelmax/simple-voice-chat/pull/457
