### ISSUE TITLE
Both "essentialCareful" rules are not working

### ISSUE THREAD

**Issue by mrniddala** [Super-Santa/EssentialAddons#52]
Hello, I am using the latest version 1.19.2.

@Redirect conflict. Skipping minitweaks.mixins.json:mob.player.drops.PlayerInventoryMixin from mod minitweaks->@Redirect::modifyAge(Lnet/minecraft/class_1657;Lnet/minecraft/class_1799;ZZ)Lnet/minecraft/class_1542; with priority 999, already redirected by essentialaddons.mixins.json:essentialCarefulDrop.PlayerInventoryMixin from mod essentialaddons->@Redirect::onDropItem(Lnet/minecraft/class_1657;Lnet/minecraft/class_1799;ZZ)Lnet/minecraft/class_1542; with priority 1000

Maybe a conflict with [MiniTweak](https://modrinth.com/mod/minitweaks)?
But as far as I can see, I don't have a similar rule activated from this mod. Only:
![image](https://user-images.githubusercontent.com/75373609/184533594-4f56be33-983b-4c78-b49b-b60b99e3faaf.png)
![image](https://user-images.githubusercontent.com/75373609/184533606-f9b01ead-ac3e-4b00-9e65-d529f52ba2de.png)

**Comment by senseiwells** [comment]
You don't seem to have the rules enabled, `essentialCarefulBreak` and `essentialCarefulDrop`

**Comment by mrniddala** [comment]
I have:

![image](https://user-images.githubusercontent.com/75373609/184533789-95a64a5f-8fb8-4c09-b531-1fe3a8be340f.png)

**Comment by senseiwells** [comment]
Ok, I'll take a look

**Comment by mrniddala** [comment]
Thank you 😊

**Comment by SouthernPixel** [comment]
yea im having the same issue :|

**Comment by SouthernPixel** [comment]
Any response? kind of afraid that this mod is abandoned :/

**Comment by aria1th** [comment]
you need to type `/subscribe carefulBreak`

**Comment by mrniddala** [comment]
I can confirm it is working.

![image](https://user-images.githubusercontent.com/75373609/187320564-904f3455-c05b-426a-a819-087989a5d143.png)

Maybe put a message if you activate the rule or add it to the rule description - everything is great now.
