### ISSUE TITLE
Camera Mode bug

### ISSUE THREAD

**Issue by muluffel** [Super-Santa/EssentialAddons#59]
when issuing the `/cs` command, since MC version 1.19.3 the following behaviour occures: 

- entering `/cs` --> Puts player into spectator mode and the actionbar says _You have been put into SPECTATOR_
- --> player can move freely around in spectator
- entering `/cs` again --> Teleports player back to original position and the actionbar says again _You have been put into SPECTATOR_ and the player doesnt get put back to survival. Entering again the player gets the message _[ERROR] Unable to get previous location_

**Comment by senseiwells** [comment]
Can you provide the version you are using and a list of other mods you are using.

**Comment by muluffel** [comment]
## Quilt 1.19.3

- Audioplayer (voicechat addon)
- Badpackets
- BlueMap
- Carpet Autocraftingtable
- Carpet Extra
- Carpet Fixes
- Essential Addons
- Fabric Carpet
- Ferritecore
- Lazydfu
- Lithium
- Memoryleakfix
- Quilted Fabric API
- Servux
- Starlight
- Syncmatica
- Voicechat
- Worldedit
- WTHIT
- Xaeros WorldMap
