### ISSUE TITLE
Bug with stackableshulkerboxesinplayerinventories

### ISSUE THREAD

**Issue by Lokemol** [Super-Santa/EssentialAddons#6]
IF YOU WANT TO CONTACT ME FOR MORE INFO, THIS IS MY DISCORD: Loke#2048

**Describe the bug**
Maybe this is a bug, or something not implemented, I have no idea, but well, if you have StackableShulkerBoxesInPlayerInventories On, you won't be able to stack shulkers automatically in containers ex: a shulker unloader won't stack the shulkers put into the chest, transfered by the hopper, you need to go there and stack them by hand, meaning that if you have that gamerule off, the items stack in the containers automatically, with carpet emptyshulkerboxes stack always, but then, you won't be able to stack shulkers with items, a downside of it, also, when you are loading shulkers, with a shulker loader, these won't stack automatically, they will go into the chest and you need to stack them by hand, so this said, it is either you have the gamerule off, and you can't stack shulkers with items, but the shulkers are sorted in stacks when they are empty, or you have it on, and shulkers are not put into stacks when transferred by hoppers into containers, but you can have stackable shulkers with items.
**General Info**
Mod Version: 1.0.5
Minecraft Version: 1.17.1

**Expected behavior**
A clear and concise description of what you expected to happen: stacking the shulkers with items via hoppers to containers, and make them stackable along with empty shulkers, because with stackableshulkerboxesinplayerinventories they don't stack, automatically, you need it off, to stack those automatically, so it would be nice if they stacked without player interaction with them, so a combination of stacking the shulkers always, either they have items or not, in containers, so that they always stack, it would be very nice, as i said, maybe its not possible, maybe it's a bug, maybe it is not, and it is a feature not added yet.

**Crash Report / Lastest Log**
[latest.log](https://github.com/Super-Santa/EssentialAddons/files/7102198/latest.log)

**Comment by senseiwells** [comment]
This is feature request not a bug

**Comment by Lokemol** [comment]
Pardon me, i just didnt know if this was supposed to happen or it was a bug, but now that i know that it is a feature request, it'd be nice to have that compatibility between carpet gamerules, a great feature actually, peace man <3
