### ISSUE TITLE
Conflict with Item Rename

### ISSUE THREAD

**Issue by Ultimushadow** [Super-Santa/EssentialAddons#68]
Hey there, I have both the Item Rename and Essential Addons mods installed for Fabric 1.20.1, both of which have a /rename command, and this mod breaks /rename entirely. Regardless of whether or not the /rename command is enabled, there's an error message when trying to use it. Personally, given that the command is the whole point of the Item Rename mod, I would rather the Essential Addon mod deactivate its command entirely so there's no conflict. Is there a way to get around this? Thanks!

**Comment by JacktheDevel0per** [comment]
It seems like the only difference between the commands is the italicized name.even then, If you want it to not be italicized then yeah, some change would be needed..

maybe adding an argument for hidden renames....

**Comment by Ultimushadow** [comment]
Item Rename also gives a /lore command which is super useful and the reason I haven't just gotten rid of it, it wasn't just the /rename command (although I think Item Rename's implementation is more customizable as you point out)
My only solution was to rip /rename out of Essential Addon to get it to work
