### ISSUE TITLE
spectatorPotionNoCountdown

### ISSUE THREAD

**Issue by the-just-luke** [Super-Santa/EssentialAddons#7]
Rule Name: spectatorPotionNoCountdown
Description: Potions do not count down while in spectator mode. 

Expected behavior: 2 examples of situations where it could improve gameplay would be if you are digging and then go in spectator but when you go back in survival, you don't have the beacon effects and have to wait for the beacons to refresh. And the other example would be that it would prevent you from going into spectator to get rid of negative potion effects after getting attacked by a wither skeleton, elder guardian, stray, husk, or shulker by just waiting.

**Comment by senseiwells** [comment]
Added for [1.16.5](https://cdn.discordapp.com/attachments/559400132710236160/886578474670751765/essentialaddons-1.16.5-1.0.5.jar)
