### ISSUE TITLE
Crash without LuckPerms

### ISSUE THREAD

**Issue by Taskeren** [Super-Santa/EssentialAddons#72]
[crash-2023-11-13_01.41.50-server.txt](https://github.com/Super-Santa/EssentialAddons/files/13328710/crash-2023-11-13_01.41.50-server.txt)

Server crashed when start without luckperms that is mentioned as optional.

**Comment by senseiwells** [comment]
I cannot reproduce this issue.
Can you please give steps to exactly reproduce this crash.

**Comment by Taskeren** [comment]
Pretty wierd, I cannot reproduce this either, but it did happened as I got the crash report.
I'll re-open this issue when I have more detailed info.
