### ISSUE TITLE
Minecart drops disappear

### ISSUE THREAD

**Issue by Aculoss** [Super-Santa/EssentialAddons#73]
When using this mod, all loot from chest minecarts and hopper minecarts disappear when broken.

**Comment by rwagner76** [comment]
Having the same issue, had to pull the mod from my server as it broke cart yeeting.

**Comment by Aculoss** [comment]
Same here, got a few cart yeeters on my farms

**Comment by senseiwells** [comment]
Fixed in https://modrinth.com/mod/essentialaddons/version/1.20.4-1.3.2
