### ISSUE TITLE
Hoppers not draining properly when mod installed

### ISSUE THREAD

**Issue by rwagner76** [Super-Santa/EssentialAddons#74]
Enabled droppers failing to move items when EssentialAddons installed.

See attached photo.  Chain of 4 hoppers into dispenser won't pass items (empty shulker boxes) from 3rd->4th hopper or into dispenser. Destroying and replacing the hopper will allow items to fill the hopper once, but if items are removed, they won't move down the chain.

All hoppers show 'enabled: true' in F3 data.

![2024-02-01_17 10 41](https://github.com/Super-Santa/EssentialAddons/assets/20705388/9bf8bc9c-77ee-4332-96cc-3739acf79eff)

I didn't notice this previously with 1.20.2 versions of EssentialAddons.  I haven't noticed this behavior with other hoppers at this point.

**Comment by senseiwells** [comment]
Could you please specify other mods you have installed? Specifically do you have lithium installed?

**Comment by rwagner76** [comment]
I do have Lithium installed.

Full list:
Carpet-Extra
Cloth-Config
Fabric-API
Fabric-Carpet
Lithium-Fabric
LuckPerms
Styled-Nicknames
Textile_Backup

**Comment by senseiwells** [comment]
This has been fixed, you can download the latest version [here](https://modrinth.com/mod/essentialaddons/version/1.20.4-1.3.3)

**Comment by rwagner76** [comment]
Awesome, thanks!
