### ISSUE TITLE
StackableShulkersWithItems destroying Items

### ISSUE THREAD

**Issue by Watergust** [Super-Santa/EssentialAddons#75]
When you burn shulkers containing items in a stack, the contents of all but one box will be destroyed.

Mods -
Carpet-extra-1.20.2-1.4.118
EssentialAddons-1.20.2-1.3.0
Fabric-api-0.91.2+1.20.2
Fabric-carpet-1.20.2-1.4.121+v231011

Carpet Settings -
AccurateBlockPlacement True
CreativeNoClip True
defaultLoggersTPS
HopperCounters True
OptimizedTNT True
StackableShulkerBoxes True
StackableShulkerComparatorOverloadFix True
StackableShulkersInPlayerInventories True
StackableShulkersWithItems True

Video Demonstrating the Bug/Issue
https://github.com/Super-Santa/EssentialAddons/assets/141888618/e6237d67-8ddd-4bb9-8305-b72f45506293

**Comment by senseiwells** [comment]
This has been fixed, you can download the latest version [here](https://modrinth.com/mod/essentialaddons/version/1.20.4-1.3.3)
