### ISSUE TITLE
Stackable shulker boxes in player inventories doesn't work

### ISSUE THREAD

**Issue by Terryotes** [Super-Santa/EssentialAddons#78]
Basically it doesn't work at all, I disabled all others by deleting them directly from the .config file and it still doesn't work, shulkers don't stack in the ground, manually or in any way

**Comment by senseiwells** [comment]
Could you provide more information such as your game version, your enabled rules and list of mods?
A video demonstrating the issue would also be helpful

**Comment by tangxizhijin** [comment]
> Could you provide more information such as your game version, your enabled rules and list of mods? A video demonstrating the issue would also be helpful

I am trying using stackshulkerboxwithitem, and stackshulkerboxininventory is true.
but it can't work, even the empty shulker can't stack.
I checked all mod one by one, and finally found this mod can't work with tweakeroo.
version: 1.20.4
the version of essential addons and tweakeroo is the newest version.

**Comment by senseiwells** [comment]
Thank you for that information. This should now be fixed [here](https://filebin.net/5fu6x6lyn9ib86sl/EssentialAddons-1.20.4-1.3.4.jar). Let me know if the issue persists.
