### ISSUE TITLE
Not any more releases, why?

### ISSUE THREAD

**Issue by luisch444** [Super-Santa/EssentialAddons#82]
### Motive

After 1.2.0 release (for 1.17.1, 1.18.2, 1.19.2, and 1.19.3) the releases have only be uploaded to modrinth. In my opinion generating at least a tag is not really time consuming an allow other developers use the project better and easier, with the addition of having more secure release procedure since the git history will be permanent.

### More information

I was not expecting not find any information about why releases where not been created. I even search for forks thinking the mantainer of the project have changed rather than having main branch out-of-date. 

### Possible solution

In the current time automation, like creating a release, it is easier than ever. So if the problem is time consuming in updating the project, shall we discuss a better way of managing the release procedure?

**Comment by senseiwells** [comment]
All releases are on modrinth to have everything in one place. 
Modrinth is much nicer as it's built for releasing mods, I can list dependencies and supported versions etc.

The main branch is out of date as I am no longer supporting older versions; see the newer branches for the updated version of the mod. If you need the source for those you can checkout those branches.

**Comment by luisch444** [comment]
I do not see modrinth having any open source / git repository option apart of the link to this git repo. I will encourage you to make at least a tag when creating versions so we have constancy of which version correspond to which commit. This allow us checking the veracity of your product, as well as easy interaction and verification with past releases. 

Of course this is not mandatory and do not have major impacts; but for me, I am making a project implementing various mods like this one, this repository is the only one at the moment that do not have constant releases. I will use the commit hashes instead of release tags, so it is not a game-breaker but it will make maintaining the project a little bit more difficult.

If it is decided to not make any tag or releases then I will hope a more understanding clarification in readmes files if possible. In the contrary if you wish to have automation via GHA or gralde, please let me know so I can lend a hand.

Anyway, thank you for your attention and understanding.
